### ISSUE TITLE
I can't make the ./config work

### ISSUE THREAD

**Issue by soluna1** [suomela/types#1]
Hi Suomela, I'm trying to make type work on my mac but.... I've installed all the dependencies and so on, Python is also installed. but when I try to run the ./config it says:
"This seems to be a Mac OS X system.

Trying to find a C compiler...
- /usr/local/bin/gcc-5           gcc 5.3.0            looks good
- /usr/bin/gcc                   gcc 4.2.1            looks good

I will use /usr/local/bin/gcc-5, which seems to be GCC version 5.3.0.
You can override it with the --cc flag.

Trying to find a Python interpreter...
I will try to run the test script src/test.py
- /usr/local/bin/python          python 2.7.11        test failed
- /usr/local/bin/python2.7       python 2.7.11        test failed
- /usr/bin/python                python 2.7.10        test failed
- /usr/bin/python2.6             python 2.6.9         test failed
- /usr/bin/python2.7             python 2.7.10        test failed

Error: could not find a Python interpreter."

Could you tell me what is wrong with this?

thanks

**Comment by suomela** [comment]
Most likely some Python modules are missing. Try to run e.g.:

```
python src/test.py
```

It should tell you which modules are missing. You should be able to use `pip` to install the missing modules.

**Comment by soluna1** [comment]
ok I'll try.

**Comment by suomela** [comment]
By the way, the latest version is hopefully much easier to set up, it should not require any additional Python modules.

**Comment by soluna1** [comment]
Thanks Suomela, I'll try that then.

**Comment by soluna1** [comment]
Sorry, I'm still on it. I've two dirs types and types-examples-master. But I don't know how to follow your instructions and make types run. I've downloaded the scripts again, this is the last version?, how can I see if so. Thanks a lot!

**Comment by suomela** [comment]
Here is a brand-new manuscript that explains how to use the tool: https://users.ics.aalto.fi/suomela/types2-d2e/

Hope this helps!

**Comment by soluna1** [comment]
Thanks for the instructions, but muy problem is with installation, I think that something is missing but I don't know how to fix it. See, after running 'make' I've got this error at the end:

> ...src/unittest.c:2:20: fatal error: assert.h: No such file or directory
> compilation terminated.
> make: **\* [build/unittest.o] Error 1

**Comment by suomela** [comment]
Have you got the command line developer tools installed? What happens if you try to run the following command:

```
xcode-select --install
```

It should either open a dialog that lets you install the developer tools, or report that the tools are already installed.

**Comment by soluna1** [comment]
Yeah, that worked. Now I'm going to try with your tutorial of examples, let's see if I'm able to make in run. Thanks a lot Suomela!!
